"""adding rating to songs

Revision ID: 06a97d56bbcc
Revises: bbbd940d0920
Create Date: 2024-05-27 04:01:17.237280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a97d56bbcc'
down_revision: Union[str, None] = 'bbbd940d0920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'rating')
    # ### end Alembic commands ###