"""Create songs table

Revision ID: bbbd940d0920
Revises: 
Create Date: 2024-05-27 03:56:31.530555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbbd940d0920'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('danceability', sa.Float(), nullable=True),
        sa.Column('energy', sa.Float(), nullable=True),
        sa.Column('key', sa.Integer(), nullable=True),
        sa.Column('loudness', sa.Float(), nullable=True),
        sa.Column('mode', sa.Integer(), nullable=True),
        sa.Column('acousticness', sa.Float(), nullable=True),
        sa.Column('instrumentalness', sa.Float(), nullable=True),
        sa.Column('liveness', sa.Float(), nullable=True),
        sa.Column('valence', sa.Float(), nullable=True),
        sa.Column('tempo', sa.Float(), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.Column('time_signature', sa.Integer(), nullable=True),
        sa.Column('num_bars', sa.Integer(), nullable=True),
        sa.Column('num_sections', sa.Integer(), nullable=True),
        sa.Column('num_segments', sa.Integer(), nullable=True),
        sa.Column('class', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')